### PR TITLE
Build and release Github workflow

### LINKED ISSUE #51: Windows executables
Hi, I would like to add this to [Scoop](https://scoop.sh/), but it seems like you have stopped providing prebuilt Windows executables in the releases. Can you bring them back? Thanks.

### LINKED ISSUE #52: Automate GitHub Releases
Releases should be created on tag push, with binaries attached. This could be used https://github.com/marvinpinto/action-automatic-releases

### PR DESCRIPTION
**Pull request by sitiom**
Closes #52 
Closes #51
Fixes https://github.com/bloznelis/typioca/pull/47#pullrequestreview-1021143376.

It works as intended on [my fork](https://github.com/sitiom/typioca).

Misc changes:
- Add dependabot to automatically update dependencies.
- Added win-arm64 build because Windows on ARM is a thing.

### CODE REVIEW

**Review by bloznelis — APPROVED** [review]
LGTM, thanks ! :+1:

**Comment by sitiom** [comment]
@bloznelis You limited the workflow only on tag push (https://github.com/bloznelis/typioca/commit/a46f82034c3029cbe97e7114ba067d3824625877)? The workflow was made so the CI only builds and creates artifacts in each commit and PR and only [releases in each tag push](https://github.com/bloznelis/typioca/blob/4c7f017078a0e076384ae6317a2c8f2e4bebb1cf/.github/workflows/ci.yml#L48).

**Comment by bloznelis** [comment]
@sitiom Yes. Why do we need built artifacts if we are not going to release them?

**Comment by sitiom** [comment]
1. Ensure pushed code is valid and successfully builds, especially on PRs
2. Try out binaries on a specific commit for testing (especially on PRs as well)

**Comment by bloznelis** [comment]
While I do understand the incentive and value of validating that code compiles and builds on PR, I think that should be a different CI step and not mashed together with release making.

But regarding the trying out binaries for specific commit – I don't think it is worth the hassle. Can't one just checkout and build the code?

**Comment by sitiom** [comment]
> While I do understand the incentive and value of validating that code compiles and builds on PR, I think that should be a different CI step and not mashed together with release making.

Can be done, it's just a hassle to create a new job and download the artifacts again. But in terms of separation, it would certainly look cleaner.

> But regarding the trying out binaries for specific commit – I don't think it is worth the hassle. Can't one just checkout and build the code?

For the end-users, it might be a hassle to them to need to have `go` installed and build the binaries themselves when they just want to try it out. Most projects provide artifacts so they could try it out without needing anything else. A common use-case would be to have a "nightly" build of some software pointing to the artifact of the latest commit (https://nightly.link/).

**Pull request merged**
