### PR TITLE
Add keyboard layout emulation

### PR DESCRIPTION
**Pull request by DanWlker**
I'm not sure if this suites what you have in mind, we can discuss about the implementation, but here's a working prototype. 

Essentially it defines a map of characters (runes) to characters, and maps them as the user types them in. If you would like to test this out you need to change the url in `config.go` for `githubLayoutsURI(fileName string)` temporarily to "https://raw.githubusercontent.com/danwlker/typioca/master/layouts/". I have tried to keep the modifications as small as possible, following the existing architecture  

Do let me know if there are any issues. Thanks

Fixes https://github.com/bloznelis/typioca/issues/81

### CODE REVIEW

**Comment by bloznelis** [comment]
Hey, code looks pretty good! You even made the layouts downloadable, which might be a bit of an overkill because they could have been just rune -> rune maps, I think. But now we could also allow users to use their custom mappings.

I have a little problem though, I changed the `githubLayoutsURI` path to the one you provided and it still lists no available layouts in the config:
image

Do you have any ideas why this might be happening?

**Comment by DanWlker** [comment]
> Hey, code looks pretty good! You even made the layouts downloadable, which might be a bit of an overkill because they could have been just rune -> rune maps, I think. But now we could also allow users to use their custom mappings.
> 
> I have a little problem though, I changed the `githubLayoutsURI` path to the one you provided and it still lists no available layouts in the config: image
> 
> Do you have any ideas why this might be happening?

Ahh I think its cause i didn't update the `currentConfigVersion`, so its still reading the old one instead of using the new default config version that has new fields, can you check if its working after this?

**Comment by bloznelis** [comment]
Yep, that was it, now it works. Regarding layouts — how did you prepare those mapping JSON files, was it done manually or semi-automated? I would like us to have Dvorak too (slight bias).

But overall this looks pretty good, I didn't find any issues, good job!

**Comment by DanWlker** [comment]
Ahhh nice, glad it worked. As for generating it, the code is this, I'm not sure how you would like to include it to the repo. The left side is the original character, the right side is the resultant character mapped.

```go
func FWriteStructToYaml[T any](stuff T) error {
	f, err := os.OpenFile(fileLocation, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	defer f.Close()
	if err != nil {
		panic(err)
	}
	enc := json.NewEncoder(f)
	if err := enc.Encode(stuff); err != nil {
		panic(err)
	}

	return nil
}

func main() {

	thing := Layout{
		Name: "Gallium",
		Mappings: map[rune]rune{
			'q': 'b',
			'w': 'l',
			'e': 'd',
			'r': 'c',
			't': 'v',
			'y': 'j',
			'u': 'y',
			'i': 'o',
			'o': 'u',
			'p': ',',
			'a': 'n',
			's': 'r',
			'd': 't',
			'f': 's',
			'h': 'p',
			'j': 'h',
			'k': 'a',
			'l': 'e',
			';': 'i',
			'z': 'q',
			'x': 'm',
			'c': 'w',
			'v': 'z',
			'b': 'x',
			'n': 'k',
			'm': 'f',
		},
	}

	FWriteStructToYaml(thing)
}

```

**Comment by bloznelis** [comment]
I see. I've done this kind of work for word lists in Clojure [here](https://github.com/bloznelis/typioca/tree/master/words), so it lives alongside in the repo, but it's not included in the binary itself. If you are happy, we can merge it and I'll take it from here.

**Comment by DanWlker** [comment]
yup sounds good, we can add dvorak later for testing

**Pull request merged**
